"""Workspace infrastructure bootstrap — per-project docker-compose.

Each project's workspace gets:
- postgres (isolated port, separate data volume)
- redis (optional)
- .env.forge file with connection URLs

Orchestrator calls ensure_workspace_infra() before first task. This writes
docker-compose.yml, starts containers, waits for readiness, and returns env
dict with DATABASE_URL / REDIS_URL for Claude subprocess + pytest env.
"""

import hashlib
import os
import pathlib
import socket
import subprocess
import time
from dataclasses import dataclass


@dataclass
class WorkspaceInfra:
    workspace_dir: str
    postgres_port: int
    redis_port: int | None
    database_url: str
    redis_url: str | None
    env: dict[str, str]
    started: bool
    error: str | None = None


def _pick_port(seed: str, low: int = 55000, high: int = 60000) -> int:
    """Deterministic port pick per project slug — stable across runs."""
    h = int(hashlib.sha256(seed.encode()).hexdigest(), 16)
    return low + (h % (high - low))


def _port_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def _compose_yaml(project_slug: str, pg_port: int, redis_port: int | None) -> str:
    pg_pass = hashlib.sha256((project_slug + "-pass").encode()).hexdigest()[:16]
    project_name = f"forge-{project_slug}"
    services = f"""services:
  postgres:
    image: postgres:16-alpine
    container_name: {project_name}-postgres
    environment:
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: {pg_pass}
      POSTGRES_DB: app
    ports:
      - "127.0.0.1:{pg_port}:5432"
    volumes:
      - forge_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forge -d app"]
      interval: 3s
      timeout: 3s
      retries: 15
"""
    if redis_port:
        services += f"""  redis:
    image: redis:7-alpine
    container_name: {project_name}-redis
    ports:
      - "127.0.0.1:{redis_port}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 10
"""
    services += "\nvolumes:\n  forge_pg_data:\n"
    return services


def _write_env_file(workspace: pathlib.Path, database_url: str, redis_url: str | None) -> None:
    content = [
        "# Auto-generated by Forge workspace_infra.py — connection URLs for this project's isolated services",
        f"DATABASE_URL={database_url}",
        f"TEST_DATABASE_URL={database_url}",
    ]
    if redis_url:
        content.append(f"REDIS_URL={redis_url}")
    (workspace / ".env.forge").write_text("\n".join(content) + "\n", encoding="utf-8")


def _wait_healthy(project_slug: str, timeout: int = 60) -> tuple[bool, str]:
    """Wait for postgres container to be healthy."""
    container = f"forge-{project_slug}-postgres"
    start = time.monotonic()
    while time.monotonic() - start < timeout:
        try:
            proc = subprocess.run(
                ["docker", "inspect", "--format", "{{.State.Health.Status}}", container],
                capture_output=True, text=True, timeout=5,
            )
            status = (proc.stdout or "").strip()
            if status == "healthy":
                return True, "healthy"
            if status == "" and proc.returncode != 0:
                # Container missing
                return False, f"inspect failed: {proc.stderr.strip()}"
        except Exception as e:
            return False, f"docker inspect error: {e}"
        time.sleep(2)
    return False, f"timeout after {timeout}s"


def ensure_workspace_infra(
    workspace_dir: str,
    project_slug: str,
    enable_redis: bool = False,
    force_restart: bool = False,
) -> WorkspaceInfra:
    """Ensure docker-compose services are running for this project's workspace.

    Idempotent — if already running and force_restart=False, returns existing info.
    """
    ws = pathlib.Path(workspace_dir)
    ws.mkdir(parents=True, exist_ok=True)

    pg_port = _pick_port(project_slug + "-pg")
    redis_port = _pick_port(project_slug + "-redis") if enable_redis else None

    pg_pass = hashlib.sha256((project_slug + "-pass").encode()).hexdigest()[:16]
    database_url = f"postgresql://forge:{pg_pass}@127.0.0.1:{pg_port}/app"
    redis_url = f"redis://127.0.0.1:{redis_port}/0" if redis_port else None

    env = {"DATABASE_URL": database_url, "TEST_DATABASE_URL": database_url}
    if redis_url:
        env["REDIS_URL"] = redis_url

    # Write compose file
    compose_path = ws / "docker-compose.forge.yml"
    compose_path.write_text(_compose_yaml(project_slug, pg_port, redis_port), encoding="utf-8")

    # Write .env.forge for Claude/pytest
    _write_env_file(ws, database_url, redis_url)

    # Start containers
    project_name = f"forge-{project_slug}"
    try:
        cmd_up = ["docker", "compose", "-p", project_name, "-f", str(compose_path), "up", "-d"]
        if force_restart:
            subprocess.run(
                ["docker", "compose", "-p", project_name, "-f", str(compose_path), "down"],
                capture_output=True, timeout=30,
            )
        proc = subprocess.run(cmd_up, cwd=str(ws), capture_output=True, text=True, timeout=120)
        if proc.returncode != 0:
            return WorkspaceInfra(
                workspace_dir=workspace_dir, postgres_port=pg_port, redis_port=redis_port,
                database_url=database_url, redis_url=redis_url, env=env, started=False,
                error=f"docker compose up failed: {proc.stderr[-500:]}",
            )
    except subprocess.TimeoutExpired:
        return WorkspaceInfra(
            workspace_dir=workspace_dir, postgres_port=pg_port, redis_port=redis_port,
            database_url=database_url, redis_url=redis_url, env=env, started=False,
            error="docker compose up timeout",
        )
    except FileNotFoundError:
        return WorkspaceInfra(
            workspace_dir=workspace_dir, postgres_port=pg_port, redis_port=redis_port,
            database_url=database_url, redis_url=redis_url, env=env, started=False,
            error="docker not found on PATH",
        )

    # Wait for health
    healthy, msg = _wait_healthy(project_slug, timeout=60)
    if not healthy:
        return WorkspaceInfra(
            workspace_dir=workspace_dir, postgres_port=pg_port, redis_port=redis_port,
            database_url=database_url, redis_url=redis_url, env=env, started=False,
            error=f"postgres not healthy: {msg}",
        )

    return WorkspaceInfra(
        workspace_dir=workspace_dir, postgres_port=pg_port, redis_port=redis_port,
        database_url=database_url, redis_url=redis_url, env=env, started=True,
    )


def stop_workspace_infra(project_slug: str, workspace_dir: str) -> bool:
    """Stop containers for a project. Returns True on success."""
    ws = pathlib.Path(workspace_dir)
    compose_path = ws / "docker-compose.forge.yml"
    if not compose_path.exists():
        return True
    project_name = f"forge-{project_slug}"
    try:
        proc = subprocess.run(
            ["docker", "compose", "-p", project_name, "-f", str(compose_path), "down"],
            capture_output=True, text=True, timeout=30,
        )
        return proc.returncode == 0
    except Exception:
        return False
