"""Contract validation middleware.

Validates POST/PATCH request bodies against Forge entity contracts,
using the same validation engine as the CLI (core/contracts.py).

API-adapted specs: IDs are auto-generated in the API, so "id" is not
required in request bodies. All other structural validation (required
fields, enums, types) mirrors core module CONTRACTS definitions.

Decisions update contract intentionally diverges from core module:
the API uses direct field updates (status, recommendation, reasoning)
instead of the CLI's action-based pattern (accept, override, defer).
"""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Any

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse

try:
    from core.contracts import validate_contract
except ImportError:
    validate_contract = None  # core/ not available — validation skipped

logger = logging.getLogger(__name__)

# Global disable via environment variable
_SKIP_ALL = os.environ.get("FORGE_SKIP_CONTRACT_VALIDATION", "").lower() == "true"

# Max request body size for contract validation (1 MB)
_MAX_BODY_SIZE = 1_000_000

# ---------------------------------------------------------------------------
# Route matching
# ---------------------------------------------------------------------------

# Match: /api/v1/projects/{slug}/{entity}
_COLLECTION_RE = re.compile(
    r"^/api/v1/projects/[^/]+/"
    r"(tasks|decisions|changes|objectives|ideas|guidelines|knowledge|lessons|ac-templates|gates)$"
)

# Match: /api/v1/projects/{slug}/{entity}/{id}
_ITEM_RE = re.compile(
    r"^/api/v1/projects/[^/]+/"
    r"(tasks|decisions|objectives|ideas|guidelines|knowledge|ac-templates)"
    r"/[^/]+$"
)

# POST routes that are NOT add/create operations — skip validation
_SKIP_SUFFIXES = (
    "/next",
    "/complete",
    "/context",
    "/commit",
    "/promote",
    "/link",
    "/unlink",
    "/instantiate",
    "/check",
)


def _should_skip(path: str) -> bool:
    """Check if this path is a special action endpoint (not add/update)."""
    if "/auth/" in path:
        return True
    return any(path.endswith(suffix) for suffix in _SKIP_SUFFIXES)


def _match_route(path: str, method: str) -> tuple[str | None, str | None]:
    """Extract (entity, operation) from request path + method.

    Returns (None, None) if the route is not subject to contract validation.
    """
    if _should_skip(path):
        return None, None

    if method == "POST":
        m = _COLLECTION_RE.match(path)
        if m:
            return m.group(1), "add"

    elif method in ("PATCH", "PUT"):
        m = _ITEM_RE.match(path)
        if m:
            return m.group(1), "update"

    return None, None


# ---------------------------------------------------------------------------
# Contract specs — API-adapted versions of core module CONTRACTS
# ---------------------------------------------------------------------------
# These mirror the core module definitions but adapted for API use:
# - "id" removed from required (auto-generated by API)
# - Lambda invariants omitted (Pydantic models handle per-field validation)
# - Enums kept for double-checking beyond Pydantic Literal types

_CONTRACTS: dict[tuple[str, str], dict[str, Any]] = {
    # -- Tasks (from core/pipeline.py) --
    ("tasks", "add"): {
        "required": ["name"],
        "optional": [
            "description", "instruction", "depends_on", "parallel",
            "conflicts_with", "skill", "acceptance_criteria",
            "type", "blocked_by_decisions", "scopes", "origin",
            "knowledge_ids", "test_requirements",
        ],
        "enums": {
            "type": {"feature", "bug", "chore", "investigation"},
        },
        "types": {
            "depends_on": list,
            "conflicts_with": list,
            "parallel": bool,
            "acceptance_criteria": list,
            "blocked_by_decisions": list,
            "scopes": list,
            "knowledge_ids": list,
            "test_requirements": dict,
        },
    },
    # NOTE: API TaskUpdate is intentionally limited vs core update-task contract.
    # Core allows updating depends_on, conflicts_with, etc. — API exposes a subset
    # matching the Pydantic model. Enum validation covers what the API accepts.
    ("tasks", "update"): {
        "required": [],
        "optional": [
            "name", "description", "instruction", "status",
            "failed_reason", "blocked_by_decisions",
        ],
        "enums": {
            "status": {"TODO", "IN_PROGRESS", "DONE", "FAILED", "SKIPPED", "CLAIMING"},
        },
        "types": {
            "blocked_by_decisions": list,
        },
    },

    # -- Decisions (from core/decisions.py) --
    ("decisions", "add"): {
        "required": ["task_id", "type", "issue", "recommendation"],
        "optional": [
            "reasoning", "alternatives", "confidence", "status",
            "decided_by", "file", "scope",
            "exploration_type", "findings", "options", "open_questions",
            "blockers", "ready_for_tracker", "evidence_refs",
            "severity", "likelihood", "mitigation_plan", "resolution_notes",
            "linked_entity_type", "linked_entity_id", "tags",
        ],
        "enums": {
            "type": {
                "architecture", "implementation", "dependency", "security",
                "performance", "testing", "naming", "convention", "constraint",
                "business", "strategy", "other", "exploration", "risk",
            },
            "confidence": {"HIGH", "MEDIUM", "LOW"},
            "status": {"OPEN", "CLOSED", "DEFERRED", "ANALYZING", "MITIGATED", "ACCEPTED"},
            "decided_by": {"claude", "user", "imported"},
            "exploration_type": {"domain", "architecture", "business", "risk", "feasibility"},
            "severity": {"HIGH", "MEDIUM", "LOW"},
            "likelihood": {"HIGH", "MEDIUM", "LOW"},
            "linked_entity_type": {"idea", "task"},
        },
        "types": {
            "alternatives": list,
            "findings": list,
            "options": list,
            "open_questions": list,
            "blockers": list,
            "evidence_refs": list,
            "tags": list,
            "ready_for_tracker": bool,
        },
    },
    # NOTE: API uses direct field updates instead of core's action-based pattern.
    # Includes risk fields (severity, likelihood, mitigation_plan) for risk-type updates.
    ("decisions", "update"): {
        "required": [],
        "optional": [
            "status", "recommendation", "reasoning",
            "decided_by", "resolution_notes",
            "severity", "likelihood", "mitigation_plan", "tags",
        ],
        "enums": {
            "status": {"OPEN", "CLOSED", "DEFERRED", "ANALYZING", "MITIGATED", "ACCEPTED"},
            "decided_by": {"claude", "user", "imported"},
            "severity": {"HIGH", "MEDIUM", "LOW"},
            "likelihood": {"HIGH", "MEDIUM", "LOW"},
        },
        "types": {
            "tags": list,
        },
    },

    # -- Changes (from core/changes.py) --
    ("changes", "add"): {
        "required": ["task_id", "file", "action", "summary"],
        "optional": [
            "reasoning_trace", "decision_ids", "lines_added",
            "lines_removed", "group_id", "guidelines_checked",
        ],
        "enums": {
            "action": {"create", "edit", "delete", "rename", "move"},
        },
        "types": {
            "reasoning_trace": list,
            "decision_ids": list,
            "lines_added": int,
            "lines_removed": int,
            "guidelines_checked": list,
        },
    },

    # -- Objectives (from core/objectives.py) --
    ("objectives", "add"): {
        "required": ["title", "description", "key_results"],
        "optional": [
            "appetite", "scope", "assumptions", "tags",
            "scopes", "derived_guidelines", "knowledge_ids",
        ],
        "enums": {
            "appetite": {"small", "medium", "large"},
            "scope": {"project", "cross-project"},
        },
        "types": {
            "key_results": list,
            "assumptions": list,
            "tags": list,
            "scopes": list,
            "derived_guidelines": list,
            "knowledge_ids": list,
        },
        "invariants": [
            (lambda item, i: len(item.get("key_results", [])) >= 1,
             "At least one key_result is required"),
            (lambda item, i: all(
                isinstance(kr, dict) and kr.get("metric") and kr.get("target") is not None
                for kr in item.get("key_results", [])
            ), "Each key_result must have 'metric' (string) and 'target' (number)"),
        ],
    },

    # -- Ideas (from core/ideas.py) --
    ("ideas", "add"): {
        "required": ["title", "description"],
        "optional": [
            "category", "priority", "tags", "related_ideas",
            "guidelines", "parent_id", "relations", "scopes",
            "advances_key_results", "knowledge_ids",
        ],
        "enums": {
            "category": {
                "feature", "improvement", "experiment",
                "migration", "refactor", "infrastructure",
                "business-opportunity", "research",
            },
            "priority": {"HIGH", "MEDIUM", "LOW"},
        },
        "types": {
            "tags": list,
            "related_ideas": list,
            "guidelines": list,
            "relations": list,
            "scopes": list,
            "advances_key_results": list,
            "knowledge_ids": list,
        },
    },
    ("ideas", "update"): {
        "required": [],
        "optional": [
            "title", "description", "status", "category",
            "priority", "rejection_reason", "merged_into",
            "tags", "related_ideas", "guidelines",
            "exploration_notes", "parent_id", "relations",
            "scopes", "advances_key_results", "knowledge_ids",
        ],
        "enums": {
            "status": {"DRAFT", "EXPLORING", "APPROVED", "REJECTED"},
            "category": {
                "feature", "improvement", "experiment",
                "migration", "refactor", "infrastructure",
                "business-opportunity", "research",
            },
            "priority": {"HIGH", "MEDIUM", "LOW"},
        },
        "types": {
            "tags": list,
            "related_ideas": list,
            "guidelines": list,
            "relations": list,
            "scopes": list,
            "advances_key_results": list,
            "knowledge_ids": list,
        },
    },

    # -- Guidelines (from core/guidelines.py) --
    ("guidelines", "add"): {
        "required": ["title", "scope", "content"],
        "optional": ["rationale", "examples", "tags", "weight", "derived_from"],
        "enums": {
            "weight": {"must", "should", "may"},
        },
        "types": {
            "examples": list,
            "tags": list,
        },
    },
    ("guidelines", "update"): {
        "required": [],
        "optional": [
            "title", "content", "status", "rationale",
            "scope", "examples", "tags", "weight", "derived_from",
        ],
        "enums": {
            "status": {"ACTIVE", "DEPRECATED"},
            "weight": {"must", "should", "may"},
        },
        "types": {
            "examples": list,
            "tags": list,
        },
    },

    # -- Knowledge (from core/knowledge.py) --
    ("knowledge", "add"): {
        "required": ["title", "category", "content"],
        "optional": [
            "scopes", "tags", "source", "linked_entities",
            "dependencies", "review_interval_days", "created_by",
        ],
        "enums": {
            "category": {
                "domain-rules", "api-reference", "architecture",
                "business-context", "technical-context", "code-patterns",
                "integration", "infrastructure",
            },
        },
        "types": {
            "scopes": list,
            "tags": list,
            "linked_entities": list,
            "dependencies": list,
            "review_interval_days": int,
        },
    },
    ("knowledge", "update"): {
        "required": [],
        "optional": [
            "title", "content", "status", "category", "scopes", "tags",
            "source", "dependencies", "review_interval_days",
            "change_reason", "changed_by",
        ],
        "enums": {
            "status": {"DRAFT", "ACTIVE", "REVIEW_NEEDED", "DEPRECATED", "ARCHIVED"},
            "category": {
                "domain-rules", "api-reference", "architecture",
                "business-context", "technical-context", "code-patterns",
                "integration", "infrastructure",
            },
        },
        "types": {
            "scopes": list,
            "tags": list,
            "dependencies": list,
            "review_interval_days": int,
        },
    },

    # -- Lessons (from core/lessons.py) --
    ("lessons", "add"): {
        "required": ["category", "title", "detail"],
        "optional": [
            "task_id", "decision_ids", "severity", "applies_to", "tags",
        ],
        "enums": {
            "category": {
                "pattern-discovered", "mistake-avoided",
                "decision-validated", "decision-reversed",
                "tool-insight", "architecture-lesson",
                "process-improvement", "market-insight",
            },
            "severity": {"critical", "important", "minor"},
        },
        "types": {
            "decision_ids": list,
            "tags": list,
        },
    },

    # -- AC Templates (from core/ac_templates.py) --
    ("ac-templates", "add"): {
        "required": ["title", "template", "category"],
        "optional": [
            "description", "parameters", "scopes", "tags",
            "verification_method",
        ],
        "enums": {
            "category": {
                "performance", "security", "quality", "functionality",
                "accessibility", "reliability", "data-integrity", "ux",
            },
        },
        "types": {
            "parameters": list,
            "scopes": list,
            "tags": list,
        },
    },
    ("ac-templates", "update"): {
        "required": [],
        "optional": [
            "title", "template", "description", "category",
            "parameters", "scopes", "tags", "verification_method",
            "status",
        ],
        "enums": {
            "category": {
                "performance", "security", "quality", "functionality",
                "accessibility", "reliability", "data-integrity", "ux",
            },
            "status": {"ACTIVE", "DEPRECATED"},
        },
        "types": {
            "parameters": list,
            "scopes": list,
            "tags": list,
        },
    },

    # -- Gates (from core/gates.py) --
    ("gates", "add"): {
        "required": ["name", "command"],
        "optional": ["required"],
        "enums": {},
        "types": {
            "required": bool,
        },
    },
}


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------

class ContractValidationMiddleware(BaseHTTPMiddleware):
    """Validate POST/PATCH request bodies against Forge entity contracts.

    Intercepts mutating requests to entity endpoints, validates the JSON
    body against the matching contract spec, and returns 422 with
    structured error details on validation failure.

    Skip mechanisms:
    - Non-entity routes are ignored
    - Special action routes (next, complete, etc.) are skipped
    - FORGE_SKIP_CONTRACT_VALIDATION=true env var disables globally
    """

    async def dispatch(self, request: Request, call_next):
        # Global disable via env var or missing core module
        if _SKIP_ALL or validate_contract is None:
            return await call_next(request)

        # Only validate mutating methods
        if request.method not in ("POST", "PATCH", "PUT"):
            return await call_next(request)

        # Only validate JSON content
        content_type = request.headers.get("content-type", "")
        if "application/json" not in content_type:
            return await call_next(request)

        # Match route to entity + operation
        entity, operation = _match_route(request.url.path, request.method)
        if entity is None:
            return await call_next(request)

        spec = _CONTRACTS.get((entity, operation))
        if spec is None:
            return await call_next(request)

        # Read request body (with size limit to avoid memory issues)
        try:
            body_bytes = await request.body()
            if not body_bytes:
                return await call_next(request)
            if len(body_bytes) > _MAX_BODY_SIZE:
                return JSONResponse(
                    status_code=413,
                    content={"detail": "Request body too large for validation"},
                )
            data = json.loads(body_bytes)
        except (json.JSONDecodeError, UnicodeDecodeError):
            # Let FastAPI/Pydantic handle JSON parse errors
            return await call_next(request)

        # Normalize to list for validate_contract
        items = data if isinstance(data, list) else [data]

        # Run contract validation
        errors = validate_contract(spec, items)
        if errors:
            logger.warning(
                "Contract validation failed for %s %s: %s",
                request.method,
                request.url.path,
                errors,
            )
            return JSONResponse(
                status_code=422,
                content={
                    "detail": "Contract validation failed",
                    "entity": entity,
                    "operation": operation,
                    "errors": errors,
                },
            )

        return await call_next(request)
